/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 652380b6713e5ec67643ab66c53eaa3d)
interface __BaseEnv_Env {
	USAGE_LEDGER: KVNamespace;
	REQUEST_RATE_LIMITER: RateLimit;
	ENVIRONMENT?: "production" | "staging";
	DEVICE_TOKENS: DurableObjectNamespace<import("./src/index").DeviceTokenRegistry>;
	SPEND_LEDGER: DurableObjectNamespace<import("./src/index").DeviceSpendLedger>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DeviceTokenRegistry" | "DeviceSpendLedger";
	}
	interface ProductionEnv {
		USAGE_LEDGER: KVNamespace;
		REQUEST_RATE_LIMITER: RateLimit;
		ENVIRONMENT: "production";
		DEVICE_TOKENS: DurableObjectNamespace<import("./src/index").DeviceTokenRegistry>;
		SPEND_LEDGER: DurableObjectNamespace<import("./src/index").DeviceSpendLedger>;
	}
	interface StagingEnv {
		USAGE_LEDGER: KVNamespace;
		REQUEST_RATE_LIMITER: RateLimit;
		ENVIRONMENT: "staging";
		DEVICE_TOKENS: DurableObjectNamespace<import("./src/index").DeviceTokenRegistry>;
		SPEND_LEDGER: DurableObjectNamespace<import("./src/index").DeviceSpendLedger>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
