/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: df83ee4d5eb185fbea201e9ed349087d)
interface __BaseEnv_Env {
	USAGE_LEDGER: KVNamespace;
	REQUEST_RATE_LIMITER: RateLimit;
	ENVIRONMENT?: "production" | "staging";
	DEVICE_TOKENS: DurableObjectNamespace<import("./src/index").DeviceTokenRegistry>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "DeviceTokenRegistry";
	}
	interface ProductionEnv {
		USAGE_LEDGER: KVNamespace;
		REQUEST_RATE_LIMITER: RateLimit;
		ENVIRONMENT: "production";
		DEVICE_TOKENS: DurableObjectNamespace<import("./src/index").DeviceTokenRegistry>;
	}
	interface StagingEnv {
		USAGE_LEDGER: KVNamespace;
		REQUEST_RATE_LIMITER: RateLimit;
		ENVIRONMENT: "staging";
		DEVICE_TOKENS: DurableObjectNamespace<import("./src/index").DeviceTokenRegistry>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
